parameters:
    GOOGLE_MAPS_API_KEY: '%env(GOOGLE_MAPS_API_KEY)%'

framework:
    secret: '%kernel.charset%'
    #csrf_protection: true
    #esi: true
    #fragments: true
    test: true
    session:
        storage_factory_id: session.storage.factory.mock_file