controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

personal_page:
    path: /page-of-{slug}
    controller: App\Controller\PersonalPageController::index
    methods: [GET]


patient_update:
    path: /patient-update
    controller: App\Controller\UpdatePatientController::index
    methods: [GET, POST]

professional_update:
    path: /professional-update
    controller: App\Controller\UpdateProfessionalController::index
    methods: [GET, POST]